### ISSUE TITLE
More comments in the Code

### ISSUE THREAD

**Issue by pntpareek** [ashakerpoor/fullyLocalElasticModel#1]
Dear ashakerpoor,

Can you please comment about the various parameters that you are using in the code also what is "dcd.h" file that you are including.

Best Regards
pntpareek

**Comment by ashakerpoor** [comment]
Dear pntpareek,

Thank you for your interest. I tried to add comments to the first few blocks of the code and explain the major parameters of the simulation. This program calculates C_ijkl, the modulus tensor, for local domains such that it is possible to obtain a distribution of C_ijkl. The indices i,j,k, and l are specified at the command line.

About the "dcd.h", it is a header file that allows you to read the dcd trajectory files into the program. dcd is a binary type outputted by some MD simulation packages such as NAMD and LAMMPS. In my case, I used trajectory files created by LAMMPS.

I hope this helps.

Best,
ashakerpoor

**Comment by pntpareek** [comment]
Dear ashakerpoor,

Thank you very much for your help. Can you please tell where can I find the "dcd.h" file? I tried to search it on the internet but did not able to find it. I also use lammps to dump trajectory but did not know about the dcd trajectory files.

Thanks again

Best Regards
pntpareek

**Comment by ashakerpoor** [comment]
Dear pntpareek,

Unfortunately, I believe I do not have the permission to release the "dcd.h" file as it was part of a work done by another contributor. I understand that to run the current version of the program you will need the dcd.h file but you can compile the program by removing the lines that import functions from this file and instead replacing them with the lines of your code that you would normally use to read in a dcd data file. I have marked such lines with comments.

I am sorry for the inconvenience. If this changes later, I will upload the dcd file on my github.

Best regards,
ashakerpoor

**Comment by pntpareek** [comment]
Dear ashakerpoor,

Thanks for adding comments. This will be helpful.

Best Regards
pntpareek
